Vagrant.configure("2") do |config|
    config.vm.box = "ros2env/ros2-humble"
    config.vm.hostname = "ros2-humble"
  
    config.vm.network "public_network"
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
        vb.name = "ROS2 Humble"
    end
  
    config.vm.network "forwarded_port", guest: 6080, host: 6080, host_ip: "127.0.0.1"
  end
  