Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "ros2-humble"

    config.vm.network "public_network"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
        vb.name = "ROS2 Humble"
    end

    config.vm.network "forwarded_port", guest: 6080, host: 6080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"

    # Copies the scripts into the VM
    config.vm.provision "file", source: "scripts/install.sh", destination: "/home/vagrant/install.sh"
    config.vm.provision "file", source: "scripts/vscode-server.sh", destination: "/home/vagrant/vscode-server.sh"

    # Make them executable and run them
    config.vm.provision "shell", inline: <<-SHELL
        chmod +x /home/vagrant/install.sh /home/vagrant/vscode-server.sh
        /home/vagrant/install.sh
        /home/vagrant/vscode-server.sh
    SHELL
end